// Soundbite manifest for Ilya Rozanov — Heated Rivalry
// Audio files live in /public/audio/ and are named by ID.
// Files are not included in the repository — see README for the extraction pipeline.

// Set hasAudio: true once the mp3 exists in public/audio/
export const soundbites = [
  {
    id: "russians-dont-blush",
    quote: "Never in life have I blushed. Russians do not do this.",
    context: "To teammate Marleau, who caught him flushing over a text from Shane",
    episode: "S01E02 — Olympians",
    category: "denial",
    audio: "/audio/russians-dont-blush.mp3",
    hasAudio: true,
  },
  {
    id: "see-you-in-final",
    quote: "You will not be so nice when we beat you. See you in final.",
    context: "To Shane Hollander on first meeting at the International Prospect Cup",
    episode: "S01E01 — Rookies",
    category: "rivalry",
    audio: "/audio/see-you-in-final.mp3",
  },
  {
    id: "bronze-medal",
    quote: "Dreaming of what? Bronze medal?",
    context: "Taunting Shane about his ambitions",
    episode: "S01E01 — Rookies",
    category: "rivalry",
    audio: "/audio/bronze-medal.mp3",
    hasAudio: true,
  },
  {
    id: "fifty-goals",
    quote: "I never said 40 goals. It's a lie. Liar told you that. I said 50.",
    context: "To a reporter correcting a misquote",
    episode: "S01E03 — Hunter",
    category: "confidence",
    audio: "/audio/fifty-goals.mp3",
    hasAudio: true,
  },
  {
    id: "cover-of-the-game",
    quote: "I'm on the cover of the fucking game.",
    context: "Reminding Shane of his status during an argument",
    episode: "S01E03 — Hunter",
    category: "confidence",
    audio: "/audio/cover-of-the-game.mp3",
  },
  {
    id: "only-one-person",
    quote: "It's true, I've been with many women, but... I have only been in love with one person.",
    context: "Quietly admitting the truth about his feelings",
    episode: "S01E04 — Rose",
    category: "tender",
    audio: "/audio/only-one-person.mp3",
  },
  {
    id: "problem-never-go-away",
    quote: "I do not want the problem to ever go away.",
    context: "When asked if his feelings for Shane are a problem he wants resolved",
    episode: "S01E04 — Rose",
    category: "tender",
    audio: "/audio/problem-never-go-away.mp3",
  },
  {
    id: "ruined-you",
    quote: "I have ruined you. No one else will do.",
    context: "To Shane",
    episode: "S01E04 — Rose",
    category: "tender",
    audio: "/audio/ruined-you.mp3",
  },
  {
    id: "panic-attack",
    quote: "Hollander, you are having a panic attack. It's just a plan to fuck.",
    context: "Cutting through Shane's anxiety with characteristic bluntness",
    episode: "S01E02 — Olympians",
    category: "blunt",
    audio: "/audio/panic-attack.mp3",
    hasAudio: true,
  },
  {
    id: "mr-hollander-perfect",
    quote: "Mr. Hollander. How does it feel to be perfect? Fucking perfect.",
    context: "Internal — Ilya watching Shane on the ice",
    episode: "S01E04 — Rose",
    category: "tender",
    audio: "/audio/mr-hollander-perfect.mp3",
  },
  {
    id: "stupid-canadian-wolf-bird",
    quote: "Fuck you and your loon. Stupid Canadian wolf bird.",
    context: "Terrified by a loon call at the cottage while holding a canoe paddle",
    episode: "S01E06 — The Cottage",
    category: "comedy",
    audio: "/audio/stupid-canadian-wolf-bird.mp3",
    hasAudio: true,
  },
  {
    id: "what-the-fuck-was-that",
    quote: "What the fuck was that?",
    context: "Ilya's reaction — the chaos he causes simply by existing",
    episode: "S01E01 — Rookies",
    category: "comedy",
    audio: "/audio/what-the-fuck-was-that.mp3",
    hasAudio: true,
  },
  {
    id: "sounds-like-wolf",
    quote: "Sounds like a fucking wolf. What the fuck bird makes a noise like that?",
    context: "Reacting to his first ever loon call",
    episode: "S01E06 — The Cottage",
    category: "comedy",
    audio: "/audio/sounds-like-wolf.mp3",
    hasAudio: true,
  },
  {
    id: "im-coming-to-the-cottage",
    quote: "I'm coming to the cottage.",
    context: "The simple declaration that carries everything",
    episode: "S01E06 — The Cottage",
    category: "tender",
    audio: "/audio/im-coming-to-the-cottage.mp3",
    hasAudio: true,
  },
  {
    id: "love-confession-russian",
    quote: "All I want is you. It's always you. I'm so in love with you, and I don't know what to do about it.",
    context: "From his Russian-language phone call to Shane after his father's funeral — the confession Shane couldn't understand",
    episode: "S01E05 — I'll Believe in Anything",
    category: "tender",
    audio: "/audio/love-confession-russian.mp3",
  },
  {
    id: "freckles",
    quote: "Your freckles are stunning.",
    context: "To Shane, with his characteristic directness",
    episode: "S01E02 — Olympians",
    category: "tender",
    audio: "/audio/freckles.mp3",
  },
  {
    id: "short-hockey-player",
    quote: "I cannot stop thinking about this short fucking hockey player.",
    context: "Internal admission about Shane",
    episode: "S01E01 — Rookies",
    category: "denial",
    audio: "/audio/short-hockey-player.mp3",
  },
]

export const categories = {
  denial: { label: "Denial", color: "#e63946" },
  rivalry: { label: "Rivalry", color: "#457b9d" },
  confidence: { label: "Confidence", color: "#f4a261" },
  tender: { label: "Tender", color: "#a8dadc" },
  blunt: { label: "Blunt", color: "#e9c46a" },
  comedy: { label: "Comedy", color: "#2a9d8f" },
}
